version: '2'
services:
  nginx:
    image: nginx:1.13.7
    volumes:
     - .:/usr/share/nginx/html
    networks:
     - globalproxy_default
     - default
    restart: always
networks:
  globalproxy_default:
    external: true
